### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by Doctorwho1909**
Add truth

### CODE REVIEW

**Comment by realtrumpwall** [comment]
This is clearly fake news created by the left to divide America. #MAGA #FakeNews

**Comment by Doctorwho1909** [comment]
take your fake hair and lick off the poop

**Comment by realtrumpwall** [comment]
> take your fake hair and lick off the poop

I will send the entire military after you. #Owned

**Comment by Doctorwho1909** [comment]
> > take your fake hair and lick off the poop
> 
> I will send the entire military after you. #Owned

sending murders won't save you

**Comment by realtrumpwall** [comment]
> > > take your fake hair and lick off the poop
> > 
> > 
> > I will send the entire military after you. #Owned
> 
> sending murders won't save you

Silly Canadian. Socialism is a cancer and capitalism is superior. Don't believe the thousands of videos of police brutality, it's clearly fake news

**Comment by realtrumpwall** [comment]
Closed because the radical left is too much to handle #Exhausted

**Pull request closed without merging**
